version: '3.8'
services:
  db:
    image: mysql:8
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 25082003
      MYSQL_DATABASE: asistencia_app
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "3004:3004"
    volumes:
      - .:/app
    command: npx nodemon server.js

volumes:
  mysqldata:
